version: '3.0'

services:
  # API Container
  api:
    container_name: webcrawler_api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      MYSQL_DATABASE_PASSWORD: some-random-gibberish # To be changed by build script
      MYSQL_DATABASE_HOST: mysql
    ports:
      - "8888:80"
    links:
      - "db:mysql"
  # Database Container
  db:
    container_name: webcrawler_database
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: some-random-gibberish # To be changed by build script
    ports:
      - "3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    ports:
    - "9998"
  # Default Web Crawler Container
  webcrawler:
    container_name: webcrawler
    build: .
    environment:
      MYSQL_DATABASE_PASSWORD: some-random-gibberish # To be changed by build script
      MYSQL_DATABASE_HOST: mysql
      TIKA_SERVER_HOST: tikaserver
    entrypoint:
      - /usr/local/bin/crawl
      - web
    ports:
      - "6800:6800"
    links:
      - "db:mysql"
      - "tikaserver:tikaserver"
    volumes:
      - ./web_logs:/var/log
  # News Sites Crawler Container
  newscrawler:
    container_name: newscrawler
    build: .
    environment:
      MYSQL_DATABASE_PASSWORD: some-random-gibberish # To be changed by build script
      MYSQL_DATABASE_HOST: mysql
      TIKA_SERVER_HOST: tikaserver
    entrypoint:
      - /usr/local/bin/crawl
      - news
    ports:
      - "6801:6800"
    links:
      - "db:mysql"
      - "tikaserver:tikaserver"
    volumes:
      - ./news_logs:/var/log

volumes:
  mysql_data:
  web_logs:
  news_logs:
