version: '3.1'

services:
  # Database Container
  mariadb:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: MySuperSecretPassword
    ports:
      - "3306"
    volumes:
      - data:/var/lib/mysql
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    restart: always
    ports:
      - "9998"
  # App Container
  app:
    container_name: app
    build: .
    restart: always
    environment:
      DB_PASSWORD: MySuperSecretPassword
      DB_HOST: mariadb
      TIKA_SERVER_HOST: tikaserver
      SCRAPY_LOG_PATH: /home/api/logs/scrapy
    ports:
      - "5000:5000"
    links:
      - mariadb
      - tikaserver
    volumes:
      - logs_api:/home/api/logs
      - logs_scrapy:/home/webcrawler/logs

volumes:
  data:
  logs_api:
  logs_scrapy: