version: '3.1'

services:
  # API Container
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      MYSQL_DATABASE_PASSWORD: some-random-gibberish # To be changed by build script
      MYSQL_DATABASE_HOST: mysql
    ports:
      - "8888:80"
    links:
      - "db:mysql"
    depends_on:
      - "db"
    volumes:
      - ./api_logs:/usr/src/api/logs
  # Database Container
  db:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: some-random-gibberish # To be changed by build script
    ports:
      - "3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    ports:
    - "9998"
  # Default Web Crawler Container
  web:
    container_name: web
    build: .
    environment:
      DB_PASSWORD: some-random-gibberish # To be changed by build script
      DB_HOST: mysql
      TIKA_SERVER_HOST: tikaserver
      SCRAPY_LOG_PATH: "/logs"
    entrypoint:
      - "/usr/local/bin/crawl"
      - web
    ports:
      - "6800:6800"
    links:
      - "db:mysql"
      - "tikaserver:tikaserver"
    depends_on:
      - "db"
      - "tikaserver"
    volumes:
      - ./web_logs:/logs
  # News Sites Crawler Container
  news:
    container_name: news
    build: .
    environment:
      DB_PASSWORD: some-random-gibberish # To be changed by build script
      DB_HOST: mysql
      TIKA_SERVER_HOST: tikaserver
      SCRAPY_LOG_PATH: "/logs"
    entrypoint:
      - "/usr/local/bin/crawl"
      - news
    ports:
      - "6801:6800"
    links:
      - "db:mysql"
      - "tikaserver:tikaserver"
    depends_on:
      - "db"
      - "tikaserver"
    volumes:
      - ./news_logs:/logs

volumes:
  mariadb_data:
  api_logs:
  web_logs:
  news_logs:
