version: '3.1'

services:
  # Database Container
  mariadb:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    restart: always
    ports:
      - "9998"
  # RabbitMQ Broker for Celery (@see celeryproject.org)
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379"
    volumes:
      - ./redis_data:/data
  # Default Web Crawler Container
  scrapyd:
    container_name: scrapyd
    build:
      context: scrapyd
    restart: always
    environment:
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb
      TIKA_SERVER_HOST: tikaserver
    ports:
      - "6800"
    links:
      - mariadb
      - tikaserver
  # API Container
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    environment:
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mariadb
      # EGG_VERSION should match the version number in setup.py otherwise egg file resolution will fail in api.tasks
      EGG_VERSION: "2.0.0"
      SCRAPYD_HOST: scrapyd
    ports:
      - "5000:5000"
    links:
      - mariadb
      - redis
      - scrapyd
    volumes:
      - ./api_logs:/home/api/logs
    command: "celery -A tasks worker --loglevel=info --pidfile=/home/api/celery.pid --logfile=/home/api/logs/celery.log"

volumes:
  mariadb_data:
  redis_data:
  api_logs:
