# Copyright (C) Abraham Aondowase Yusuf - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
# Written by Abraham Aondowase Yusuf <aaondowasey@gmail.com>, April 2018
version: '3.1'

services:
  # Database Container
  mariadb:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: MySuperSecretPassword
    ports:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    restart: always
    ports:
      - "9998"
  # App Container
  app:
    container_name: app
    build: .
    restart: always
    environment:
      DB_PASSWORD: MySuperSecretPassword
      DB_HOST: mariadb
      TIKA_CLIENT_ONLY: True
      TIKA_SERVER_ENDPOINT: http://tikaserver:9998
    ports:
      - "5000:5000"
    links:
      - mariadb
      - tikaserver
    volumes:
      - ./api_logs:/home/api/logs
      - ./media_store:/tmp

volumes:
  data:
  api_logs:
  media_store: