version: '3.1'

services:
  # Database Container
  database:
    container_name: db
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306"
    volumes:
      - "./mariadb_data:/var/lib/mysql"
  # Tika Server Container
  tikaserver:
    container_name: tikaserver
    image: logicalspark/docker-tikaserver
    restart: always
    ports:
      - "9998"
  # RabbitMQ Broker for Celery (@see celeryproject.org)
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    environment:
      HOSTNAME: ${RABBITMQ_HOST}
      RABBITMQ_DEFAULT_USER: webcrawler
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_HIPE_COMPILE: 1
  # Default Web Crawler Container
  scrapyd:
    container_name: scrapyd
    build:
      context: scrapyd
    restart: always
    environment:
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mysql
      TIKA_SERVER_HOST: tikaserver
    ports:
      - "6800"
    links:
      - "database:mysql"
      - "tikaserver:tikaserver"
  # API Container
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_HOST: mysql
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: webcrawler
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "5000"
    links:
      - "database:mysql"
      - "rabbitmq:${RABBITMQ_HOST}"
    volumes:
      - "./api_logs:/home/api/logs"

volumes:
  mariadb_data:
  api_logs:
